### ISSUE TITLE
'Tags' column is also needed, but not mentioned on this line

### ISSUE THREAD

**Issue by Kota-Matsuda** [mustakimali/keep2notion#3]
https://github.com/mustakimali/keep2notion/blob/7e447a04c0882a250c5f2c910f7c0163bde3492e/README.md?plain=1#L13

**Comment by Kota-Matsuda** [comment]
Thanks for the great app;)
I was able to migrate successfully!
There was a stumbling block, so I'm sharing it as an Issue.
The README says that the database fields must have 'Created' and 'Edited' fields, but in addition, if the 'Tags' field was missing, I got an execution error.
Hopefully this field will be added to the requirements as well.

**Comment by mustakimali** [comment]
Thanks for reporting this. I thought Notion adds the `Tags` column automatically on all new databases however there might be situations where it won't. So I have clarified in the requirement list.
